Cookie Cuts je mobilna puzzle igra i u ovom notebooku istražujemo kvalitet podataka koje smo dobili u csv-u i retenciju igrača na osnovu kapije. Postoji kapija u igri koja tera igrače da nakon određenog nivoa (30) da čeka ili da plati da bi nastavio dalje. 

Radimo A/B testing da vidimo da li pomeranje kapije utiče na retenciju igrača.

A grupa - gate_30
B grupa - gate_40

In [11]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('data/cookie_cats.csv')
df.head()

   userid  version  sum_gamerounds  retention_1  retention_7
0     116  gate_30               3        False        False
1     337  gate_30              38         True        False
2     377  gate_40             165         True        False
3     483  gate_40               1        False        False
4     488  gate_40             179         True         True

In [18]:
print('Broj redova i kolona: \n', df.shape)
print('Tipovi podataka: \n', df.dtypes)
print('Broj nedostajućih vrednosti po koloni: \n', df.isnull().sum())
print('Broj duplikata \n', df['userid'].duplicated().sum())

Broj redova i kolona:
 (90189, 5)
Tipovi podataka:
 userid            int64
version             str
sum_gamerounds    int64
retention_1        bool
retention_7        bool
dtype: object
Broj nedostajućih vrednosti po koloni:
 userid            0
version           0
sum_gamerounds    0
retention_1       0
retention_7       0
dtype: int64
Broj duplikata
 0

In [19]:
df['version'].value_counts()

version
gate_40    45489
gate_30    44700
Name: count, dtype: int64

In [20]:
df.groupby('version')[['retention_1', 'retention_7']].mean().round(4)

         retention_1  retention_7
version
gate_30       0.4482       0.1902
gate_40       0.4423       0.1820